# Generated by Django 2.2.6 on 2020-04-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('modified_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('email_send', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tables.Table')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['date', 'confirmed'],
            },
        ),
    ]
